### ISSUE TITLE
DataLoader worker exited unexpectedly.

### ISSUE THREAD

**Issue by HaseebSarwary** [rfonod/deepsleep2#1]
Hi There,

I received this error when running your code, I have downloaded all the file repositories and followed it through but still receiving this error. What is the solution?

![Code Error](https://user-images.githubusercontent.com/95762070/185420599-d3b9c931-1fd6-4fe8-9cf4-a2f3318cc016.jpg)

**Comment by rfonod** [comment]
Hi, it seems that there is an issue with PyTorch's DataLoader module. Did you download the whole training folder (±135 GB) and placed it inside your local `deepsleep2/data` folder?
